[package]
name = "monster-fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.10", features = ["x86_64-unix"] }
ark-groth16 = "0.4"
ark-bn254 = "0.4"
ark-std = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
criterion = "0.5"
