name = "cicada71-bbs"
main = "worker.js"
compatibility_date = "2025-01-01"

[env.production]
kv_namespaces = [
  { binding = "KV", id = "cicada71_state" }
]

[[env.production.durable_objects.bindings]]
name = "BBS_SESSION"
class_name = "BBSSession"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
