[package]
name = "game-shard-20"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game_20"
path = "src/game_20.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/game_20.rs"

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = 3
lto = true
