[package]
name = "game-shard-12"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game_12"
path = "src/game_12.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/game_12.rs"

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = 3
lto = true
