[package]
name = "game-shard-13"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game_13"
path = "src/game_13.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/game_13.rs"

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = 3
lto = true
